# Generated by Django 3.2.8 on 2022-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
