# Generated by Django 3.2.8 on 2022-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20221017_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='ali',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='ozon',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='wb',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='ym',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
